# Generated by Django 2.1.4 on 2019-01-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAccounts', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='file',
            new_name='files',
        ),
    ]
